# Generated by Django 3.1 on 2020-08-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccines',
            new_name='Vaccine',
        ),
    ]
