# Generated by Django 3.1 on 2020-08-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20200809_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='Submisson_date',
            new_name='Submission_date',
        ),
    ]
